ui: tape
tunnel:
  type: ngrok
capabilities:
  record-video: false
  video-upload-on-pass: false
  record-screenshots: false
browsers:
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: chrome
    version: latest
  - name: ipad
    version: 8.4..latest
  - name: iphone
    version: 8.4..latest
